app = "telegram-weather-bot"
primary_region = "waw"

[build]
  image = "python:3.11-slim"

[env]
  TELEGRAM_TOKEN = "${TELEGRAM_TOKEN}"
  OPENMETEO_URL = "${OPENMETEO_URL}"
  DB_PATH = "/data/weather.db"
  TZ_OFFSET = "${TZ_OFFSET}"
